"""add company

Revision ID: 55b93794f33b
Revises: 920013aaf87f
Create Date: 2023-02-21 15:45:49.752756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b93794f33b'
down_revision = '920013aaf87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_name', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=80), nullable=False),
    sa.Column('number', sa.String(length=6), nullable=False),
    sa.Column('neighborhood', sa.String(length=80), nullable=False),
    sa.Column('postal_code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
