"""add company coluns

Revision ID: 6fd139c7f7e7
Revises: 55b93794f33b
Create Date: 2023-02-21 21:39:22.700713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd139c7f7e7'
down_revision = '55b93794f33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
