"""alter user include name

Revision ID: 920013aaf87f
Revises: 26935c14d47d
Create Date: 2023-02-19 21:45:06.414697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920013aaf87f'
down_revision = '26935c14d47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
