"""project2

Revision ID: a51191d2f630
Revises: 4c697bbd1997
Create Date: 2023-03-05 19:38:41.059298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51191d2f630'
down_revision = '4c697bbd1997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
